meta_product_name: "Flutter"
meta_title: "Flutter - A Social Gambling App"
meta_description: "Bet with your friends on literally anything"
meta_image: "cover.jpg" # should exist in `app/assets/images/`
